### ISSUE TITLE
LlaMa2 support?

### ISSUE THREAD

**Issue by popshi** [katsumiok/pyaskit#2]
Hello, 
do you have plan to support LlaMa2 and the other open LLM?
Thanks.

**Comment by katsumiok** [comment]
Thank you for showing interest in pyaskit. While we plan to support Llama2 and other LLMs, the priority is not high at the moment. However, we're constantly evaluating our roadmap based on user feedback and community interest. Please feel free to contribute or provide further suggestions to help shape the project's direction.

**Comment by katsumiok** [comment]
Llama2 is now supported in version 1.2.0.
