### ISSUE TITLE
Why no haiku support?

### ISSUE THREAD

**Issue by Emasoft** [katsumiok/pyaskit#6]
Why no haiku support? I need claude haiku for some quick data estraction (names, job title, address) from documents. Haiku is the only one not too expensive and fast enough for the job (can process hundreds of paragraphs per minute). Your pyaskit is ideal for integrating such quick text processing tasks in a python script. Being the model more convenient on the market, I expected it to be your first choice.

**Comment by katsumiok** [comment]
Thank you for your feedback on adding Haiku support to pyaskit. We're pleased to announce that we have updated pyaskit to include Haiku integration.

To help you get started, we've added the example/information_extraction.py script that demonstrates how to use Haiku with pyaskit for information extraction tasks. We encourage you to give it a try and let us know about your experience.

Your feedback is valuable to us as we continue to improve pyaskit. Please don't hesitate to share any further suggestions or report any issues you may encounter while using Haiku with pyaskit.

We appreciate your contribution and hope you find the Haiku support beneficial for your projects.

**Comment by Emasoft** [comment]
You solved it all, even adding examples! You are really amazing! Thank you!🙏 😲
I will do my best to give you some feedback!🫡
I truly believe in pyaskit potential!
AI integration in python needs to be as easy and pythonic as possible. 
I also wanted to suggest you a decorator, but this is for later, now I need to test it out.😉
